print("*******************************")
print("Calculadora con una sola variable")
print("*******************************\n")
print("****************")
print("Menú de opciones")
print("****************\n")
print("1.Suma")
print("2.Resta")
print("3.Multiplicación")
print("4.División")
print("5.División entera")
print("6.Exponenciación")
print("7.Módulo o resto")
opcion = int(input("Ingrese la opción: "))
if opcion == 1:
    print("Seleccionaste Suma")
    numero = int(input("Ingrese número 1: "))
    numero += int(input("Ingrese número 2: "))
    print("El resultado de la suma es: ",numero)    
elif opcion == 2:
    print("Seleccionaste Resta")
    numero = int(input("Ingrese número 1: "))
    numero -= int(input("Ingrese número 2: "))
    print("El resultado de la resta es: ",numero)
elif opcion == 3:
    print("Seleccionaste multiplicación")
    numero = int(input("Ingrese número 1: "))
    numero *= int(input("Ingrese número 2: "))
    print("El resultado de la multiplicación es: ",numero)
elif opcion == 4:
    print("Seleccionaste división")
    numero = float(input("Ingrese número 1: "))
    numero /= float(input("Ingrese número 2: "))
    print("El resultado de la división es: ",round(numero,2))
elif opcion == 5:
    print("Seleccionaste división entera")
    numero = float(input("Ingrese número 1: "))
    numero //= float(input("Ingrese número 2: "))
    print("El resultado de la división entera es: ",numero)
elif opcion == 6:
    print("Seleccionaste exponenciación")
    numero = flot(input("Ingrese número 1: "))
    numero **= float(input("Ingrese número 2: "))
    print("El resultado de la exponenciación es: ",numero)
elif opcion == 7:
    print("Seleccionaste módulo")
    numero = int(input("Ingrese número 1: "))
    numero %= int(input("Ingrese número 2: "))
    print("El resultado del módulo es: ",numero)
else:
    print("Vuelve a intentar")
